/**
 * 1. Personal Assistant Architecture Flow:
 * > User interacts with Assistant.
 * > Assistant decides whether it needs to:
 *   1. Get events from calendar
 *   2. Create a new event
 *
 * > Flow:
 *    [User]-------------> [Assistant] -------------> [User]
 * Do I have any              ^  ^
 * meeting today?             |  |
 *                      +-----+  +-----+
 *                      |              |
 *                      V              V
 *              [get event tool]  [create event tool]
 *                      |              |
 *                      |              |
 *                      +-----+ +------+
 *                            | |
 *                            | |
 *                            V V
 *                      [Google Calendar]
 */

/**
 * LangGraph Flow:
 *                          +-----------+
 *                          | __start__ |
 *                          +-----------+
 *                                |
 *                                V
 *                          +-----------+
 *               +--------->| Assistant |
 *               |          +-----------+
 *               |                |
 *               |          +-----------+
 *               |          |           |
 *               |          V           V
 *               |      +------+    +---------+
 *               +------| Tool |    | __end__ |
 *                      +------+    +---------+
 *                          |
 *                          |
 *                  +--------------+
 *                  |              |
 *                  V              V
 *         +----------------+ +-------------------+
 *         | get event tool | | create event tool |
 *         +----------------+ +-------------------+
 *
 * Assistant does NOT directly talk to calendar.
 * It uses tools as a middle layer.
 */

/**
 * PROJECT IMPLEMENTATION PLAN
 *
 * Step 1: Project Setup
 *         - Install dependencies
 *         - Configure .env variables
 *
 * Step 2: Setup LLM
 *         - Initialize ChatGroq
 *         - Bind tools to model
 *
 * Step 3: Define Graph Nodes
 *         - Assistant Node (LLM)
 *         - Tool Node
 *
 * Step 4: Add Conditional Routing
 *         - Decide when to call tools
 *
 * Step 5: Build Graph
 *         - Connect nodes
 *         - Define edges
 *
 * Step 6: Add Memory
 *         - Use MemorySaver
 *         - Maintain conversation thread
 *
 * Step 7: Build Terminal UI
 *         - Read user input
 *         - Invoke graph
 *         - Print response
 *
 * Step 8: Test Full Agent
 *         - Create meeting
 *         - Fetch meeting
 *         - Validate memory
 */

import readline from 'node:readline/promises';
import { ChatGroq } from '@langchain/groq';
import { createEventTool, getEventsTool } from './tools';
import { END, MemorySaver, MessagesAnnotation, StateGraph } from '@langchain/langgraph';
import { ToolNode } from '@langchain/langgraph/prebuilt';
import type { AIMessage } from '@langchain/core/messages';

/**
 * Step 1: Initialize LLM and Bind Available Tools
 * - ChatGroq is our reasoning engine.
 * - bindTools() allows model to generate tool calls.
 */
const tools = [createEventTool, getEventsTool];

const model = new ChatGroq({
    apiKey: process.env.GROQ_API_KEY,
    model: 'openai/gpt-oss-120b',
    temperature: 0,
}).bindTools(tools);

/**
 * Step 2: Define Assistant Node
 * - This node calls the LLM.
 * - It receives conversation state.
 * - It returns AI response message.
 */
async function callModel(state: typeof MessagesAnnotation.State) {
    const response = await model.invoke(state.messages);
    return { messages: [response] };
}

/**
 * Step 3: Define Tool Node
 * - Automatically executes tool calls generated by AI.
 * - Routes execution to the correct tool function.
 */
const toolNode = new ToolNode(tools);

/**
 * Step 4: Define Conditional Routing Logic
 * - Checks the last AI message.
 * - If tool_calls exist → go to "tools" node.
 * - Otherwise → finish execution (__end__).
 */
function shouldContinue(state: typeof MessagesAnnotation.State) {
    const lastMessage = state.messages[state.messages.length - 1] as AIMessage;

    if (lastMessage.tool_calls?.length) {
        return 'tools';
    }

    return '__end__';
}

/**
 * Step 5: Build the Graph
 * - MessagesAnnotation: manages message state
 * - addNode()          : register nodes
 * - addEdge()          : fixed transitions
 * - addConditionalEdges(): dynamic routing based on LLM output
 */
const graph = new StateGraph(MessagesAnnotation)
    .addNode('assistant', callModel)
    .addNode('tools', toolNode)
    .addEdge('__start__', 'assistant')
    .addEdge('tools', 'assistant')
    .addConditionalEdges('assistant', shouldContinue, {
        __end__: END,
        tools: 'tools',
    });

/**
 * Step 6: Attach Memory Layer
 * - MemorySaver stores conversation state between turns.
 * - thread_id keeps the session consistent.
 */
const checkpointer = new MemorySaver();

/**
 * Step 7: Compile Graph
 * - Finalizes the graph into an executable application.
 */
const app = graph.compile({ checkpointer });

/**
 * Step 8: Start Terminal Interface
 * - Reads user input continuously in a loop.
 * - Injects current datetime and timezone into system prompt.
 * - Sends messages to the graph and prints AI response.
 * - Type /bye to exit.
 */
async function main() {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    const config = { configurable: { thread_id: '1' } };

    console.log('🤖 Google Calendar Assistant started. Type /bye to exit.\n');

    while (true) {
        const userInput = await rl.question('You: ');

        if (userInput.trim() === '/bye') {
            console.log('Goodbye! 👋');
            break;
        }

        if (!userInput.trim()) {
            continue;
        }

        try {
            const currentDateTime = new Date().toLocaleString('sv-SE').replace(' ', 'T');
            const timeZoneString = Intl.DateTimeFormat().resolvedOptions().timeZone;

            /**
             * Step 9: Invoke Graph
             * - System message provides temporal context so the LLM
             *   can correctly resolve "today", "tomorrow", etc.
             * - User message carries the actual request.
             * - Result contains the full message history; we print the last one.
             */
            const result = await app.invoke(
                {
                    messages: [
                        {
                            role: 'system',
                            content: `  You are a smart personal assistant that helps manage Google Calendar.
                                        Current datetime: ${currentDateTime}
                                        Current timezone: ${timeZoneString}

                                        When creating events:
                                        - If the user does not specify a duration, default to 1 hour.
                                        - If the user says "fill details yourself", infer a reasonable summary and time.
                                        - attendee displayName is optional — only include it if the user provides a name.
                                        - Always confirm what you created with the event title, time, and Meet link.

                                        When fetching events:
                                        - Use a broad search query if the user is not specific.
                                        - Summarize events clearly: title, time, attendees, and Meet link if available.`,
                        },
                        {
                            role: 'user',
                            content: userInput,
                        },
                    ],
                },
                config
            );

            const lastMessage = result.messages[result.messages.length - 1];
            console.log('\nAI:', lastMessage.content, '\n');
        } catch (err) {
            console.error('Error invoking graph:', err);
        }
    }

    rl.close();
}

main();