import React from 'react'

/**
 * Title Metadata:
*/

/**
 * What is a Page Title?
 * > A page title is the text you see:
 *   - On the browser tab
 *   - In Google Search results
 *   - In bookmarks and history
 * > Example:
 *   - Home | MyApp
 *   - Blog | MyApp
 *   - Login | MyApp
 * > The title is extremely important for:
 *   - SEO
 *   - User Experience
 *   - Branding
*/

/**
 * How Next.js handles titles meta?
 * > In Next.js, the title is not just a simple thing.
 * > You get a powerful system with three models:
 *   a. Default title
 *   b. Template title
 *   c. Absolute title
 * > Think of this like a hierarchy + override system
*/

/**
 * Default System (Base/Fallback Title)
 * 1. What is a Default Title?
 *    > The main app title
 *    > Used when no page-specific title exists
 *    > Acts as a fallback.
 * 
 * 2. Example:
 *    > export const metadata = {
 *        title: "MyApp",
 *      };
 *    > Result:
 *      - If a page does NOT define its own title
 *      - Browser tab will show - MyApp
 * 
 * 3. When should you use default title?
 *    > Very small apps
 *    > Landing pages
 *    > Simple projects
 *      (Think of it as your base identity)
*/

/**
 * Template Title (VVI)
 * 1. What is a Template Title?
 *    > A template title is a reusable pattern.
 *    > Example pattern:
 *      <Page Name> | MyApp
 *    > Instead of manually writing this everywhere, Next.js does it 
 *      for you automatically.
 * 
 * 2. Template Syntax:
 *    export const metadata = {
 *      title: {
 *        template: "%s | MyApp",
 *        default: "MyApp",
 *      },
 *    };
 *    
 * 3. Output Example :
 *    > Page Title   :  Final Browser Title
 *      a. Blog      :  Home | MyApp
 *      b. About     :  Blog | MyApp
 *      c. (no title):  MyApp
 * 
 * 4. When should you use Template Titles?
 *    > Medium to large apps
 *    > Multiple pages
 *    > SEO-focused applications
*/


/**
 * Absolute Title (Full Override Mode)
 * 1. What is an Absolute Title?
 *    > Completely ignores default and template
 *    > Sets the final title exactly as written
 * 
 * 2. Example:
 *    > export const metadata = {
 *        title: {
 *          absolute: "Login to MyApp",
 *        },
 *      };
 *    > Browser tab will show: Login to MyApp
 * 
 * 3. When should you use Absolute Title?
 *    > Special pages only:
 *      - Login
 *      - Signup
 *      - Error Pages (404, 500)
 *      - Legal/Privacy Pages
 *    > Use sparingly, not everywhere
*/

/**
 * Layout vs Page Title 
 * > Priority Order: pages.js title > layout.js title
 * > Meaning:
 *   - Page-level metadata always overrides
 *   - Layout metadata acts as a default structure
 * 
 * Example:
 * a. layout.js
 *    export const metadata = {
 *      title: {
 *        template: "%s | MyApp",
 *        default: "MyApp",
 *      },
 *    };
 *    
 * b. pages.js
 *    export const metadata = {
 *      title: "Blog",
 *    };
 *    
 * c. Final browser title:
 *    > Blog | MyApp
*/

/**
 * Best Practices:
 * > Recommended Setup:
 *   a. layout.js     : Use template + dafault
 *   b. pages.js      : Use simple string titles
 *   c. Special Pages : Use absolute only when needed
*/


export const metadata = {
  title:{
    default:"Auth | Chai or Code",
    template: "%s | Chai or Code",
    absolute: "",
  },
  description: 'Generated by create next app',
}
const AuthLayout = ({children}) => {
  return (
    <div>
        {children}
    </div>
  )
}

export default AuthLayout