import Image from "next/image";

/**
 * Metadata & SEO:
 * > Metadata is extra information about your webpage, that is hidden in
 *   html head and users don't see it directly.
 * > We need this because:
 *   - Better metadata = higher ranking
 *   - Social media sharing
 *   - Browser tab title
 * > Examples:
 *   - Page title (<title>)
 *   - Description (<meta name="description">)
 *   - Open Graph tags (used by whatsapp, linkedin previews)
 *   - SEO-related info
 * 
 * In short, Metadata tells Google + Browser + Social Media what your 
 * page is about.
*/

/**
 * Why metadata is important?
 * Think like this:
 * > Who uses metadata      Why
 *   a. Browser             :  Shows page title on tab
 *   b. Google              :  Ranking + Search Preview
 *   c. Social Media        :  Link Preview (image, title, desc)
 *   d. Accessibility tools :  Better understanding of page
 * > So yes, metadata = SEO + UX + Sharing
*/

/**
 * Two types of Metadata:
 * Next.js gives us two ways to add metadata:
 * 1. Static Metadata
 * 2. Dynamic Metadata
*/

/**
 * Static Metadata:
 * 1. What is Static Metadata?
 *    > Metadata that never changes
 *    > Same for every user
 *    > Known at build time
 * 
 * 2. Best for:
 *    > Home Page
 *    > About Page
 *    > Contact Page
 *    > Marketing Pages
 * 
 * 3. How to write Static Metadata?
 *    > export const metadata = {
 *        title: "Home Page",
 *        description: "Welcome to our website",
 *      };
 * 
 * 4. Where can you use it?
 *    a. layout.js : Common metadata for many pages
 *    b. page.js   : Page-specific metadata
 * 
 *    Example: Layout Level Metadata
 *    > export const metadata = {
 *        title: "Metadata and og images",
 *        description: "Generated by create next app"
 *      }
 *    > This applies to all pages inside this layout.
 * 
 * 5. When should you use static metadata?
 *    > Page content does not depended on data
 *    > No API call needed
 *    > SEO content is fixed
 *    > Rule of thumb: If metadata is known beforehand, go static.
*/

/**
 * Dynamic Metadata: (Data-Based)
 * 1. What is Dynamic Metadata?
 *    > Metadata that changes
 *    > Depends on:
 *      - Route params
 *      - API response
 *      - Database data
 * 
 * 2. Example:
 *    > Blog Post Title
 *    > Product Page
 *    > User Profile Page
 * 
 * 3. Why Static Metadata fails here?
 *    > Imagine:
 *      - /blog/what-is-node
 *      - /blog/what-is-react
 *    > Same title for all blogs? Bad SEO
 *    > Each blog needs its own title
 *    > That's where dynamic metadata comes in.
 * 
 * 4. How dynamic metadata works
 *    > Next.js gives a special function:
 *      export async function generateMetadata({ params }) {
 *        return {
 *          title: "...",
 *          description: "...",
 *        };
 *      }
 *    > Key Point:
 *      - This function runs before page renders
 *      - Can call APIs
 *      - Can use route programs
 * 
 * 5. Example:
 *    > export async function generateMetadata({ params }) {
 *        const blog = await fetchBlog(params.slug);
 *      
 *        return {
 *          title: blog.title,
 *          description: blog.summary,
 *        };
 *      }
 *    > Now every blog page has unique SEO metadata
*/

/**
 * Remember:
 * 1. Cannot mix static and dynamic for same route.
 * 2. Metadata works only in Server Component like page.js and layout.js
*/


export default function Home() {
  return (
    <div className="font-sans grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
      <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
        <Image
          className="dark:invert"
          src="/next.svg"
          alt="Next.js logo"
          width={180}
          height={38}
          priority
        />
        <ol className="font-mono list-inside list-decimal text-sm/6 text-center sm:text-left">
          <li className="mb-2 tracking-[-.01em]">
            Get started by editing{" "}
            <code className="bg-black/[.05] dark:bg-white/[.06] font-mono font-semibold px-1 py-0.5 rounded">
              app/page.js
            </code>
            .
          </li>
          <li className="tracking-[-.01em]">
            Save and see your changes instantly.
          </li>
        </ol>

        <div className="flex gap-4 items-center flex-col sm:flex-row">
          <a
            className="rounded-full border border-solid border-transparent transition-colors flex items-center justify-center bg-foreground text-background gap-2 hover:bg-[#383838] dark:hover:bg-[#ccc] font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 sm:w-auto"
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              className="dark:invert"
              src="/vercel.svg"
              alt="Vercel logomark"
              width={20}
              height={20}
            />
            Deploy now
          </a>
          <a
            className="rounded-full border border-solid border-black/[.08] dark:border-white/[.145] transition-colors flex items-center justify-center hover:bg-[#f2f2f2] dark:hover:bg-[#1a1a1a] hover:border-transparent font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 w-full sm:w-auto md:w-[158px]"
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Read our docs
          </a>
        </div>
      </main>
      <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
        <a
          className="flex items-center gap-2 hover:underline hover:underline-offset-4"
          href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image
            aria-hidden
            src="/file.svg"
            alt="File icon"
            width={16}
            height={16}
          />
          Learn
        </a>
        <a
          className="flex items-center gap-2 hover:underline hover:underline-offset-4"
          href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image
            aria-hidden
            src="/window.svg"
            alt="Window icon"
            width={16}
            height={16}
          />
          Examples
        </a>
        <a
          className="flex items-center gap-2 hover:underline hover:underline-offset-4"
          href="https://nextjs.org?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <Image
            aria-hidden
            src="/globe.svg"
            alt="Globe icon"
            width={16}
            height={16}
          />
          Go to nextjs.org →
        </a>
      </footer>
    </div>
  );
}
