/**
 * Cookies:
 * > Cookies are a way to store data on the client side, similar to local 
 *   storage, session storage, and Indexed DB, but they have some key 
 *   differences:
 *   - Storage Limit: Not more than 4KB
 *   - Creation     : Cookies can be created:
 *                    a. By the server (using the Set-Cookie header)
 *                    b. By client-side JavaScript (document.cookie)
 *   - Format       : Key-Value Pair (Both are stored as strings)
 * 
 * Example:
 * > sessionId=abc123
 *
 * > Since cookies are sent with every request to the server,
 *   they can slightly increase request size and affect performance
 *   if too many cookies are stored.
*/

/**
 * Cookie Attributes:
 * 1. HttpOnly
 *    - This attribute prevents JavaScript from accessing the cookie.
 *    - It protects sensitive cookies (like session tokens) from
 *      XSS (Cross-Site Scripting) attacks.
 *
 *    Example:
 *      Set-Cookie: sessionId=abc123; HttpOnly
 *
 *    If a cookie is HttpOnly, it can only be accessed by the server.
 *
 *    To send cookies with cross-site requests:
 *      fetch → credentials: "include"
 *      axios → withCredentials: true
 *
 * 2. SameSite
 *    - Controls whether cookies are sent with cross-site requests.
 *    - Helps protect against CSRF (Cross-Site Request Forgery) attacks.
 *
 *    a. SameSite=Strict
 *       - Cookie is only sent when the request originates
 *         from the same site.
 *       - Maximum protection but may break some flows.
 *
 *    b. SameSite=Lax
 *       - Cookie is sent with same-site requests and some
 *         cross-site navigation requests (like clicking a link).
 *
 *    c. SameSite=None
 *       - Cookie is sent with all requests, including cross-site.
 *       - Must also include the Secure attribute.
 *
 * 3. Secure
 *    - Ensures the cookie is only sent over HTTPS connections.
 *    - Prevents cookies from being transmitted over insecure HTTP.
 *
 *
 * 4. Max-Age
 *    - Specifies how long the cookie should remain valid.
 *    - The value is defined in seconds.
 *
 *    Example:
 *      Max-Age=3600 → Cookie expires in 1 hour.
 *
 *  5. Expires
 *    - Defines the exact date and time when the cookie should expire.
 *
 *    Example:
 *      Expires=Wed, 21 Oct 2026 07:28:00 GMT
 * 
 * 6. Path
 *    - Specifies the URL path where the cookie is valid.
 *
 *    Example:
 *      Path=/app
 *
 *    This cookie will only be sent to:
 *      /app
 *      /app/dashboard
 *
 *    But NOT to:
 *      /profile
 *
 * 7. Domain: 
 *    - Specifies the domain for which the cookie is valid. 
 *    - To make it available for all subdomains, use Domain=.codersgyan.com.
*/


/**
 * Why Cookies Are Needed:
 * 1. Authentication
 *    - Cookies store session IDs or tokens so that users
 *      remain logged in across multiple requests.
 *
 * 2. User Preferences
 *    - Cookies store user preferences such as:
 *        language
 *        theme (dark/light mode)
 *        settings
 *
 * 3. Tracking
 *    - Third-party cookies may track user activity across
 *      websites to improve advertising and analytics.
*/


/**
 * ETag (Entity Tag)
 * > ETag is an HTTP response header generated by the server.
 * > It acts like a fingerprint for a specific version of a resource.
 * > ETags help browsers determine whether a cached resource
 *   has changed on the server.
 *
 *
 * How ETag Works:
 * 1. The client requests a resource (for example, a webpage).
 * 
 * 2. The server responds with the resource and an ETag value.
 *    Example:
 *      ETag: "abc123"
 *
 * 3. The browser stores this ETag along with the cached resource.
 *
 * 4. When the client requests the resource again, it sends:
 *      If-None-Match: "abc123"
 *
 * 5. The server compares this ETag with the current resource version.
 *    If the resource has NOT changed:
 *        → Server responds with:
 *          HTTP 304 Not Modified
 *    If the resource HAS changed:
 *        → Server sends the updated resource and a new ETag.
 *
 *
 * Types of ETags:
 * 1. Strong ETags
 *    - Resource must be byte-for-byte identical.
 * 2. Weak ETags
 *    - Resource is considered the same even if minor
 *      byte-level changes exist.
 *
 *
 * Why ETags Are Useful
 * - Reduce bandwidth usage
 * - Improve page loading speed
 * - Reduce unnecessary data transfer
*/


/**
 * TLS (Transport Layer Security)
 * > TLS is a cryptographic protocol used to secure communication
 *   between a client (browser) and a server.
 * > It encrypts data so that attackers cannot read or modify
 *   the transmitted information.
 *
 * 
 * TLS vs SSL
 * - SSL (Secure Sockets Layer) was the original encryption protocol.
 * - SSL is now outdated and considered insecure.
 * - TLS is the modern and secure replacement for SSL.
 *
 * > Even though TLS is used today, many people still refer to
 *   HTTPS encryption as "SSL".
 *
 * 
 * HTTPS and TLS:
 * > HTTPS is simply HTTP running over TLS encryption.
 * > Example:
 *   HTTP  → Not encrypted
 *   HTTPS → Encrypted using TLS
 *
 * Supported TLS Versions:
 * 1. HTTP/1.0 and HTTP/1.1
 *    - Can technically use TLS 1.0–1.3
 *    - TLS 1.2 or TLS 1.3 should be used because
 *      older versions are insecure.
 * 2. HTTP/2
 *    - Requires TLS 1.2 or TLS 1.3
 * 3. HTTP/3
 *    - Uses only TLS 1.3
 *
 *
 * Why TLS Is Important:
 * > TLS provides three major security guarantees:
 *   1. Encryption
 *      - Protects data from being read by attackers.
 *   2. Authentication
 *      - Confirms the server's identity using certificates.
 *   3. Integrity
 *      - Ensures data is not modified during transmission.
 */