/**
 * 1. Why TanStack Query is perfect for Next.js?
 *    > Next.js apps:
 *      - Fetch data often
 *      - Have client components
 *      - Need caching
 *      - Need refetch on navigation
 *    > TanStack Query gives:
 *      - Smooth client-side data handling
 *      - Smart caching b/w pages
 *      - Instant UI updates
 *      - Less manual code
 *    > It complements Next.js perfectly
 * 
 * 2. Why do we need a Query Provider?
 *    > TanStack Query needs one global place to:
 *      - Store cache
 *      - Track Queries
 *      - Share data across app
 *    > That's where QueryClientProvider comes in.
 * 
 * 3. What is QueryClientProvider?
 *    > Think of it like this:
 *      - React Context for Server data
 *      - Wraps your app once
 *      - Enables queries everywhere
 *    > Without it, queries won't work
 *    > With it, everything connects
*/

/**
 * 1. Where do we initialize it in Next.js?
 *    > Best Place: app/layout.js
 *    > Why?
 *      - Loaded once
 *      - Wraps entire app
 *      - Shared cache across pages
 *    > Same logic as ThemeProvider or AuthProvider.
 * 
 * 2. What happens after setup?
 *    > Once Query Provider is set:
 *      - Any component can use queries
 *      - Data is cached automatically
 *      - Multiple components share data
 *      - Refetching is automatic
 *    > Zero prop drilling. Zero duplication.
 * 
 * 3. Mental Model:
 *    - useState: UI State
 *    - TanStack Query: Server State
 *    - Query Key     : Data identity
 *    - Provider      : Global cache manager
 *      (Once this clicks, data handling becomes easy)
*/

/**
 * Step-1: Installation
 * > Install Next.js : 
 * > Install tanstack: npm i @tanstack/react-query
 * > npm run dev
 * 
 * Step-2: Create QueryClientProvider Setup in component folder
 * > Create query-provider.js
 * 
 * Step-3: 
 * > Wrap pass layout.js to QueryClientProvider
 * > Means, Wrap your entire app into client-side query provider.
*/

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/components/query-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
        {children}
        </QueryProvider>
      </body>
    </html>
  );
}
