/**
 * Autogenerating Clients:
 * 1. What it is?
 *    > A code library that talks to your API automatically.
 *    > Generated from OpenAPI spec.
 *    > Can be JS, TS, Python, Java, etc.
 *    > Handles endpoints, params, request/response types, so you don't
 *      write fetch or axios manually.
 * 
 * 2. When to use?
 *    > You want to call your API from another project without writing
 *      HTTP requests by hand.
 *    > You want typed clients in TypeScript.
 *    > You want consistency across projects/teams.
 *    > You want to reduce errors by letting the generator handle endpoints,
 *      parameters, and response formats.
 *    > Example:
 * 
 *      import { UserApi } from './ts-client';
 *      const api = new UserApi();
 *      const users = await api.getUsers(); // no manual fetch/axios
 * 
 * 3. How do they work together?
 *    a. JSDoc:
 *       > Generates OpenAPI spec from code comments.
 *       > Keep API docs in sync with code.
 * 
 *    b. Swagger UI:
 *       > Displays OpenAPI spec in browser.
 *       > Interactive docs, testing endpoints.
 * 
 *    c. Autogenerated client:
 *       > Generates code to call API automatically.
 *       > Use API in React, Node, or other apps.
*/


/**
 * What problem does it solve?
 * > Imagine you build a restaurant kitchen (your backend API). 
 * > Now customers (frontend developers) want to order food. 
 * > You have two options:
 *   a. Manual Way (The Old Method)
 *      You give customers:
 *      - A menu (API endpoints list)
 *      - Ingredients list (data formats)
 *      - But they have to cook everything themselves from scratch!
 *      - Problem: Every customer needs to learn cooking, make mistakes,
 *                 waste time.
 *   b.Auto-Generated Clients (The Smart Method)
 *     You give customers:
 *     - Pre-cooked meals ready to eat!
 *     - Just heat and serve (import and use)
 *     - Solution: Customers get exactly what they need, no cooking required!
*/

/**
 * Real Example: Todo App API
 * > Your Backend (The Kitchen):
 *   You built these endpoints
 *   1. GET /todos - Get all todos
 *   2. POST /todos - Create new todo
 *   3. PUT /todos/:id - Update todo
 *   4. DELETE /todos/:id - Delete todo
 * 
 * The Problem: Multiple Customers
 * > You have:
 *   1. Web app (React developer)
 *   2. Mobile app (React Native developer)
 *   3. Desktop app (Electron developer)
 *   4. Third-party integrations (other companies)
 * > Each needs to write the same HTTP code to talk to your API!
 * 
 * > The Magic Solution: Auto-Generated Clients
 *   1. Instead of everyone writing this (everyone write manually):
 *      const response = await fetch('http://localhost:3000/todos', {
 *        method: 'POST',
 *        headers: {
 *          'Content-Type': 'application/json',
 *          'Authorization': 'Bearer token123'
 *        },
 *        body: JSON.stringify({
 *          title: 'Buy milk',
 *          completed: false
 *        })
 *      });
 *      
 *      const data = await response.json();
 *      if (!response.ok) throw new Error(data.message);
 *    
 *   2. They can just write this (Auto-Generated Client):
 *      import { TodoAPI } from 'todo-client';
 *      
 *      const todo = await TodoAPI.createTodo({
 *        title: 'Buy milk',
 *        completed: false
 *      });
 * 
 *   3. How it works?
 *      > You Write Your Backend with Documentation
 *      > Generate OpenAPI Specification
 *      > Generate Client Libraries
 *        - openapi-generator-cli generate -i swagger.json -g typescript-axios -o ./ts-client
 *        - This creates todo-client (TS)
 *      > Developers Use the Client:
 *        a. TS/Node:
 *           import { TodoAPI } from 'todo-client';
 *           const todo = await TodoAPI.createTodo({
 *             title: 'Buy milk',
 *             completed: false
 *           });
 *        b. ReactJS:
 *           import { TodoAPI } from 'todo-client';
 *           const todos = await TodoAPI.getTodos();
 *        c. Python:
 *           from todo_client import TodoAPI
 *           todos = TodoAPI.get_todos()
 *        d. Java:
 *           TodoAPI api = new TodoAPI();
 *           List<Todo> todos = api.getTodos();
 *  
*/

/**
 * Project Setup:
 * 1. Install Tools:
 *    > These packages do the auto-generation magic:
 *      npm install swagger-ui-express swagger-jsdoc
 *      npm install -g @openapitools/openapi-generator-cli
 *    > What each package does:
 *      a. swagger-ui-express   : Shows the beautiful UI
 *      b. swagger-jsdoc        : Reads magic comments and creates OpenAPI spec
 *      c. openapi-generator-cli: 
 *         - Reads OpenAPI spec 
 *         - Generates client code in your chosen language
 * 
 * 2. Get Your API Specification
 *    > Your server already provides this! Visit:
 *      http://localhost:3000/api-docs/json
 *    > Save this JSON to a file:
 *      a. Method-1: Using curl (in terminal)
 *         curl http://localhost:3000/api-docs/json -o openapi-spec.json
 *      b. Method-2: Using browser
 *         - Visit http://localhost:3000/api-docs/json
 *         - Save the page as "openapi-spec.json" 
 * 
 * 3. Generate TS Client:
 *    # This one command does all the magic!
 *    > openapi-generator-cli generate -i swagger.json -g typescript-axios -o ./ts-client
 *      a. -g typescript-axios: generates TS client using Axios.
 *      b. -o ./ts-client     : output folder
 * 
 *    # What it creates:
 *      ts-client/
 *      ├── api.ts           # All API methods
 *      ├── index.ts         # Main export
 *      ├── configuration.ts # Configuration
 *      ├── git_push.sh      # Helper script
 *      ├── README.md        # Instructions
 *      └── ...              # Other generated files
 * 
*/

import express from 'express';
import swaggerUi from 'swagger-ui-express';
import swaggerJsdoc from 'swagger-jsdoc';

const app = express();
const port = 3000;
app.use(express.json());

/* SECTION 1: SWAGGER CONFIGURATION */
const swaggerOptions = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'User API',
      version: '1.0.0',
      description: 'API to manage users with auto-generated Swagger docs'
    }
  },
  apis: ['./server.ts']  // Scan this file for @swagger comments
};

const swaggerSpec = swaggerJsdoc(swaggerOptions);


/* SECTION 2: OUR DATA STORE */
let users = [
  { id: 1, name: 'John Doe' },
  { id: 2, name: 'Jane Doe' }
];


/* SECTION 3: MAGIC COMMENTS + CODE */

/**
 * @swagger
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       required:
 *         - id
 *         - name
 *       properties:
 *         id:
 *           type: integer
 *           description: Unique identifier of the user
 *         name:
 *           type: string
 *           description: Name of the user
 *       example:
 *         id: 1
 *         name: John Doe
 */

/**
 * @swagger
 * /users:
 *   get:
 *     summary: Get a list of users
 *     description: Retrieve all users or filter by name
 *     tags: [Users]
 *     parameters:
 *       - in: query
 *         name: name
 *         schema:
 *           type: string
 *         required: false
 *         description: Filter users by name
 *         example: John
 *     responses:
 *       200:
 *         description: List of users
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/User'
 *             example:
 *               - id: 1
 *                 name: John Doe
 *               - id: 2
 *                 name: Jane Doe
 */
app.get('/users', (req, res) => {
  const { name } = req.query;
  if (name) {
    const filteredUsers = users.filter(user =>
      user.name.toLowerCase().includes(name.toString().toLowerCase())
    );
    res.json(filteredUsers);
  } else {
    res.json(users);
  }
});

/**
 * @swagger
 * /users:
 *   post:
 *     summary: Add a new user
 *     description: Create a new user with a unique id and name
 *     tags: [Users]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/User'
 *           example:
 *             id: 3
 *             name: Alice Smith
 *     responses:
 *       201:
 *         description: User created successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/User'
 *       400:
 *         description: Bad request - missing required fields
 */
app.post('/users', (req, res) => {
  const { id, name } = req.body;
  if (!id || !name) {
    return res.status(400).json({
      error: 'Bad Request',
      message: 'id and name are required'
    });
  }

  /* Check if user already exists */
  if (users.find(user => user.id === id)) {
    return res.status(409).json({
      error: 'Conflict',
      message: `User with id ${id} already exists`
    });
  }

  const newUser = { id, name };
  users.push(newUser);
  res.status(201).json(newUser);
});

/* SECTION 4: DISPLAY THE MAGIC UI */
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));


/* SECTION 5: Raw JSON spec (important for client generation!) */
app.get('/api-docs/json', (req, res) => {
  res.json(swaggerSpec);
});

/* SECTION 6: START THE SERVER */
app.listen(port, () => {
  console.log('SERVER STARTED SUCCESSFULLY');
  console.log(`API Base URL: http://localhost:${port}`);
  console.log(`Documentation: http://localhost:${port}/api-docs`);
  console.log(`OpenAPI Spec: http://localhost:${port}/api-docs/json`);
  console.log(`Get Users: http://localhost:${port}/users`);
  console.log(`Search Users: http://localhost:${port}/users?name=John`);
});


/**
 * Alternative: Generate Other Language Clients
 * # Python client
 * openapi-generator-cli generate \
 *   -i openapi-spec.json \
 *   -g python \
 *   -o ./python-client
 * 
 * # JavaScript client
 * openapi-generator-cli generate \
 *   -i openapi-spec.json \
 *   -g javascript \
 *   -o ./js-client
 * 
 * # Java client
 * openapi-generator-cli generate \
 *   -i openapi-spec.json \
 *   -g java \
 *   -o ./java-client
*/